# VulnProbe - Network Vulnerability Scanner
# Stage 1: Port Scanner with Service Detection
# Author: Adithya9x

import socket
import datetime
import nmap
import requests
import os
import webbrowser

def resolve_target(target):
    try:
        ip = socket.gethostbyname(target)
        return ip
    except:
        print("[-] Invalid target. Could not resolve hostname.")
        exit()

def get_service(port):
    try:
        service = socket.getservbyport(port)
        return service
    except:
        return "Unknown Service"

def nmap_scan(target, port):
    try:
        nm = nmap.PortScanner()
        nm.scan(target, str(port), arguments='-sV')
        state = nm[target]['tcp'][port]['state']
        service = nm[target]['tcp'][port]['name']
        version = nm[target]['tcp'][port]['version']
        product = nm[target]['tcp'][port]['product']
        return {
            'state': state,
            'service': service,
            'product': product,
            'version': version
        }
    except:
        return None
def check_cve(product, version):
    try:
        query = f"{product} {version}"
        url = "https://services.nvd.nist.gov/rest/json/cves/2.0"
        params = {
            "keywordSearch": query,
            "resultsPerPage": 5
        }
        response = requests.get(url, params=params, timeout=10)
        data = response.json()

        cve_list = []
        if "vulnerabilities" in data:
            for item in data["vulnerabilities"]:
                cve_id = item["cve"]["id"]
                description = item["cve"]["descriptions"][0]["value"]
                
                severity = "UNKNOWN"
                if "metrics" in item["cve"]:
                    if "cvssMetricV31" in item["cve"]["metrics"]:
                        severity = item["cve"]["metrics"]["cvssMetricV31"][0]["cvssData"]["baseSeverity"]
                    elif "cvssMetricV2" in item["cve"]["metrics"]:
                        severity = item["cve"]["metrics"]["cvssMetricV2"][0]["baseSeverity"]
                
                cve_list.append({
                    "id": cve_id,
                    "description": description[:100],
                    "severity": severity
                })
        return cve_list
    except Exception as e:
        return []
    
def generate_report(target, ip, scan_results, start_time):
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>VulnProbe Report - {target}</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #1e1e2e; color: #e0e0e0; padding: 30px; }}
            h1 {{ color: #00d9ff; border-bottom: 2px solid #00d9ff; padding-bottom: 10px; }}
            .summary {{ background: #2a2a3e; padding: 15px; border-radius: 8px; margin-bottom: 20px; }}
            .port-block {{ background: #2a2a3e; margin: 15px 0; padding: 15px; border-radius: 8px; border-left: 4px solid #00d9ff; }}
            .port-title {{ font-size: 18px; font-weight: bold; color: #00d9ff; }}
            .cve-high {{ background: #4a1c1c; border-left: 4px solid #ff4444; padding: 10px; margin: 8px 0; border-radius: 5px; }}
            .cve-medium {{ background: #4a3c1c; border-left: 4px solid #ffaa44; padding: 10px; margin: 8px 0; border-radius: 5px; }}
            .cve-low {{ background: #1c3a4a; border-left: 4px solid #44aaff; padding: 10px; margin: 8px 0; border-radius: 5px; }}
            .cve-id {{ font-weight: bold; }}
            .no-cve {{ color: #66ff66; font-style: italic; }}
            footer {{ margin-top: 30px; color: #888; font-size: 12px; }}
        </style>
    </head>
    <body>
        <h1>🔍 VulnProbe - Vulnerability Assessment Report</h1>
        <div class="summary">
            <p><b>Target:</b> {target} ({ip})</p>
            <p><b>Scan Date:</b> {start_time}</p>
            <p><b>Open Ports Found:</b> {len(scan_results)}</p>
        </div>
    """

    for result in scan_results:
        html += f"""
        <div class="port-block">
            <div class="port-title">Port {result['port']} - {result['service']}</div>
            <p>{result.get('product', '')} {result.get('version', '')}</p>
        """
        if result.get('cves'):
            for cve in result['cves']:
                css_class = "cve-high" if cve['severity'] in ["HIGH", "CRITICAL"] else "cve-medium" if cve['severity'] == "MEDIUM" else "cve-low"
                html += f"""
                <div class="{css_class}">
                    <span class="cve-id">{cve['id']}</span> - {cve['severity']}<br>
                    {cve['description']}...
                </div>
                """
        else:
            html += '<p class="no-cve">No known CVEs found.</p>'
        html += "</div>"

    html += f"""
        <footer>Generated by VulnProbe | Adithya9x | {datetime.datetime.now()}</footer>
    </body>
    </html>
    """

    filename = f"VulnProbe_Report_{target.replace('.', '_')}.html"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"\n[+] Report saved as: {os.path.abspath(filename)}")
    
    full_path = os.path.abspath(filename)
    webbrowser.open(f"file://{full_path}")
    print(f"[+] Opening report in your default browser...")
    
    return filename
    
def scan_port(target, port):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1)
        result = sock.connect_ex((target, port))
        sock.close()
        if result == 0:
            return True
        else:
            return False
    except:
        return False

def run_scanner(target, start_port, end_port):
    ip = resolve_target(target)

    print("-" * 50)
    print(f"  VulnProbe - Network Vulnerability Scanner")
    print(f"  Target   : {target} ({ip})")
    print(f"  Ports    : {start_port} to {end_port}")
    print(f"  Started  : {datetime.datetime.now()}")
    print("-" * 50)

    open_ports = []
    scan_results = []
    start_time = datetime.datetime.now()

    for port in range(start_port, end_port + 1):
        print(f"  Scanning port {port}...", end="\r")
        if scan_port(ip, port):
            service = get_service(port)
            nmap_info = nmap_scan(ip, port)
            
            result_entry = {"port": port, "service": service}
            
            if nmap_info:
                product = nmap_info['product']
                version = nmap_info['version']
                print(f"  [OPEN] Port {port:5} --> {service:15} | {product} {version}")
                result_entry["product"] = product
                result_entry["version"] = version
                
                if product and version:
                    print(f"         Checking CVE database...")
                    cves = check_cve(product, version)
                    result_entry["cves"] = cves
                    if cves:
                        for cve in cves:
                            print(f"         [VULNERABLE] {cve['id']} - {cve['severity']} - {cve['description']}...")
                    else:
                        print(f"         No known CVEs found.")
            else:
                print(f"  [OPEN] Port {port:5} --> {service:20}")
            
            open_ports.append((port, service))
            scan_results.append(result_entry)

    print("-" * 50)
    print(f"  Scan complete. {len(open_ports)} open port(s) found.")
    print("-" * 50)
    
    if scan_results:
        generate_report(target, ip, scan_results, start_time)
    
    return open_ports

target = input("Enter target IP or hostname: ")
start_port = int(input("Enter start port: "))
end_port = int(input("Enter end port: "))

run_scanner(target, start_port, end_port)